#
# Travis CI configuration file
#
# ICRAR - International Centre for Radio Astronomy Research
# (c) UWA - The University of Western Australia, 2018
# Copyright by UWA (in the framework of the ICRAR)
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307  USA
#

language: cpp

# In Linux we cache the gsl binary version
os:
  - linux
cache:
 directories:
  - gsl/2.4

# We try with both GNU and LLVM
# When running with gcc-6 we also collect coverage information
# and upload it to coveralls
jobs:
 include:
  - os: linux
    dist:
      - xenial
    compiler: gcc
    before_install:
      # We "source" it because it exports variables
      - source .travis/before_install_xenial.sh
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-6, doxygen, libgsl-dev, rapidjson-dev, libboost1.58-all-dev]
    env: CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 CUDA_ENABLED=OFF PYTHON=python3
  - os: linux
    dist:
      - xenial
    compiler: gcc
    before_install:
      # We "source" it because it exports variables
      - source .travis/before_install_xenial.sh
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-6, doxygen, libgsl-dev, rapidjson-dev, libboost1.58-all-dev]
    env: CC=/usr/bin/gcc-6 CXX=/usr/bin/g++-6 CUDA=9 PYTHON=python3
  - os: linux
    dist:
      - bionic
    compiler: gcc
    before_install:
      - source .travis/before_install_bionic.sh
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-7, doxygen, casacore-dev, rapidjson-dev, libgsl-dev, libboost1.65-all-dev]
    env: CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 CUDA=10 PYTHON=python3
  - os: linux
    dist:
      - focal
    compiler: gcc
    before_install:
      - source .travis/before_install_focal.sh
    addons:
     apt:
      sources: ubuntu-toolchain-r-test
      packages: [g++-9, doxygen, casacore-dev, rapidjson-dev, libgsl-dev, libboost1.71-all-dev]
    env: CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 CUDA=11 PYTHON=python3 CMAKE_RUN_CLANG_TIDY=ON

install:
  - source .travis/configure.sh
  - source .travis/build.sh

script:
  - source .travis/test.sh